#!/bin/sh

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
    # Run your tests here before allowing the push
    # If tests fail, exit with a non-zero status code to prevent the push
    npx jest || exit 1
fi

exit 0
